### ISSUE TITLE
Fatal error in validation.php

### ISSUE THREAD

**Issue by jojocahill2712** [scorpionslh/ACL#3]
After copying the files over to the appropriate directories and changing the application folder to the necessary folder I receive the following error when visiting the validation controller.

Fatal error: Can't use function return value in write context in C:\wamp\www\cp\1.0.0\controllers\validation.php on line 127

PHP Ver. 5.4.16

**Comment by scorpionslh** [comment]
i will see about this, tnks

2015-02-01 19:26 GMT-02:00 jojocahill2712 <notifications@github.com>:

> After copying the files over to the appropriate directories and changing
> the application folder to the necessary folder I receive the following
> error when visiting the validation controller.
>
> Fatal error: Can't use function return value in write context in
> C:\wamp\www\cp\1.0.0\controllers\validation.php on line 127
>
> PHP Ver. 5.4.16
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scorpionslh/ACL/issues/3>.
>



-- 
Att. Marcus Paulo Mazzon Dias
Desenvolvimento de Sistemas e Sites.
www.marcusp.com.br

**Comment by marcuspmd** [comment]
Try again.
